Repository stackabletech/docker-images, pull requests merged in 2021-11, with the labels that each got.

#8 Zookeeper -> ZooKeeper typos
  README.adoc
Labels: priority/low

#10 Add missing trino authorizer and hive s3 jars
  hive/Dockerfile
  trino/Dockerfile
  trino/stackable/conf/config.properties
  trino/stackable/conf/jvm.config
  trino/stackable/conf/node.properties
Labels: priority/high

#13 Remove product package version from path
  conf.py
  druid/Dockerfile
  hadoop/Dockerfile
  hbase/Dockerfile
  hive/Dockerfile
  kafka/Dockerfile
  nifi/Dockerfile
  spark/Dockerfile
  spark/stackable/jmx/config.yaml
  trino/Dockerfile
  trino/stackable/jmx/config.yaml
  trino/stackable/jmx/jmx_exporter.yaml
  zookeeper/Dockerfile
Labels: priority/critical, type/enhancement

#15 Fixed trino image.
  trino/Dockerfile
Labels: priority/critical

#16 Fix nifi copy script
  nifi/stackable/bin/copy_assets
Labels: priority/critical

#19 Removed zookeeper 3.4.x, adapted kafka 2.6/7/8.x to use the latest patch
  conf.py
Labels: priority/high

#21 Install Druid Prometheus extension
  druid/Dockerfile
Labels: type/enhancement

#23 Fix missing hive hadoop jar
  hive/Dockerfile
Labels: priority/critical, type/bug
