Repository stackabletech/docker-images, pull requests merged in 2023-11, with the labels that each got.

#497 Add hbase-operator-tools to the HBase image
  CHANGELOG.md
  conf.py
  hbase/Dockerfile
  hbase/licenses/HBASE_OPERATOR_TOOLS_LICENSE
  hbase/stackable/bin/hbck2
  hbase/upload_new_hbase-operator-tools_version.sh
Labels: customer-request

#498 Fix path substitution in the hbck2 script
  CHANGELOG.md
  hbase/Dockerfile
Labels: type/bug

#454 Created initial version of retrieval script for postgresql jdbc drivers
  hive/upload_new_postgres_driver_version.sh
Labels: status/blocker

#505 fix(hive): Update postgresql driver to 42.6.0
  CHANGELOG.md
  hive/Dockerfile
Labels: changelog/highlight, release/2023-11
