Repository stackabletech/docker-images, pull requests merged in 2024-10, with the labels that each got.

#799 feat(superset): Add needed Python libs for OIDC
  superset/Dockerfile
Labels: customer-request

#891 feat(airflow): Add Python libs needed for OIDC
  airflow/Dockerfile
Labels: customer-request, scheduled-for/2024-11

#902 chore(ubi-rust-builder): Bump Rust toolchain to 1.81.0
  ubi8-rust-builder/Dockerfile
  ubi9-rust-builder/Dockerfile
Labels: scheduled-for/2024-11
