Repository stackabletech/docker-images, pull requests merged in 2025-05, with the labels that each got.

#1091 chore(ubi-rust-builders): Update container images ahead of Stackable Release 25.7.0
  .github/ISSUE_TEMPLATE/update-base-ubi-rust-builders.md
  .github/workflows/ubi-rust-builder.yml
  CHANGELOG.md
  ubi8-rust-builder/Dockerfile
  ubi9-rust-builder/Dockerfile
Labels: scheduled-for/25.7.0

#1103 chore(opa): Update versions ahead of 25.7.0
  .github/workflows/mirror.yaml
  CHANGELOG.md
  opa/Dockerfile
  opa/versions.py
  stackable-devel/Dockerfile
Labels: status/blocker

#916 Change default user id and gid
  CHANGELOG.md
  conf.py
Labels: scheduled-for/25.7.0

#1124 chore: stop building kcat image
  .github/workflows/build_kafka-testing-tools.yaml
  .github/workflows/build_kafka.yaml
  .github/workflows/build_kcat.yaml
  .scripts/update_readme_badges.sh
  CHANGELOG.md
  README.md
Labels: release-note/action-required, release/25.7.0
